-- Leitura do catálogo (somente SELECT) usada para gerar e VERIFICAR a baseline.
-- Produz um único JSON {parte1, funcoes, parte3} com a mesma forma de
-- supabase/baseline/catalogo_producao_20260929.json.
with tabs as (
  select c.oid, n.nspname, c.relname, c.relreplident
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname in ('public','app_private') and c.relkind in ('r','p')
),
cols as (
  select t.oid, string_agg(format('  %I %s%s%s%s', a.attname, format_type(a.atttypid,a.atttypmod),
     case when a.attgenerated='s' then ' GENERATED ALWAYS AS ('||pg_get_expr(d.adbin,d.adrelid)||') STORED'
          when d.adbin is not null then ' DEFAULT '||pg_get_expr(d.adbin,d.adrelid) else '' end,
     case when a.attidentity='a' then ' GENERATED ALWAYS AS IDENTITY' when a.attidentity='d' then ' GENERATED BY DEFAULT AS IDENTITY' else '' end,
     case when a.attnotnull then ' NOT NULL' else '' end), E',\n' order by a.attnum) cols
  from tabs t join pg_attribute a on a.attrelid = t.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
  group by t.oid
)
select json_build_object(
 'parte1', json_build_object(
   'tabelas', (select string_agg(format(E'CREATE TABLE %I.%I (\n%s\n);', t.nspname, t.relname, c.cols), E'\n\n' order by t.nspname, t.relname) from tabs t join cols c on c.oid = t.oid),
   'restricoes', (select string_agg(format('ALTER TABLE ONLY %I.%I ADD CONSTRAINT %I %s;', t.nspname, t.relname, k.conname, pg_get_constraintdef(k.oid)), E'\n' order by t.nspname, t.relname, k.contype, k.conname)
      from tabs t join pg_constraint k on k.conrelid = t.oid where k.contype in ('p','u','c','x')),
   'fks', (select string_agg(format('ALTER TABLE ONLY %I.%I ADD CONSTRAINT %I %s;', t.nspname, t.relname, k.conname, pg_get_constraintdef(k.oid)), E'\n' order by t.nspname, t.relname, k.conname)
      from tabs t join pg_constraint k on k.conrelid = t.oid where k.contype = 'f'),
   'indices', (select string_agg(pg_get_indexdef(i.indexrelid)||';', E'\n' order by t.nspname, t.relname, ic.relname)
      from tabs t join pg_index i on i.indrelid = t.oid join pg_class ic on ic.oid = i.indexrelid
      where not exists (select 1 from pg_constraint k where k.conindid = i.indexrelid)),
   'replica', (select string_agg(format('ALTER TABLE %I.%I REPLICA IDENTITY %s;', nspname, relname, case relreplident when 'f' then 'FULL' when 'n' then 'NOTHING' end), E'\n') from tabs where relreplident in ('f','n'))
 ),
 'funcoes', (select json_agg(json_build_object('nome', n.nspname||'.'||p.proname||'('||pg_get_function_identity_arguments(p.oid)||')', 'def', pg_get_functiondef(p.oid), 'acl', coalesce(p.proacl::text,''), 'owner', pg_get_userbyid(p.proowner)) order by n.nspname, p.proname, pg_get_function_identity_arguments(p.oid))
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname in ('public','app_private') and p.prokind in ('f','p')
      and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')),
 'parte3', json_build_object(
   'triggers_baseline_v2', (select json_agg(pg_get_triggerdef(t.oid)||';' order by n.nspname, c.relname, t.tgname) from pg_trigger t join pg_class c on c.oid = t.tgrelid join pg_namespace n on n.oid = c.relnamespace where not t.tgisinternal and (n.nspname in ('public','app_private') or (n.nspname = 'auth' and t.tgname = 'on_auth_user_created'))),
   'rls', (select json_agg(format('ALTER TABLE %I.%I ENABLE ROW LEVEL SECURITY;', n.nspname, c.relname) || case when c.relforcerowsecurity then format(' ALTER TABLE %I.%I FORCE ROW LEVEL SECURITY;', n.nspname, c.relname) else '' end order by n.nspname, c.relname) from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname in ('public','app_private') and c.relkind = 'r' and c.relrowsecurity),
   'policies', (select json_agg(format('CREATE POLICY %I ON %I.%I AS %s FOR %s TO %s%s%s;', p.policyname, p.schemaname, p.tablename, p.permissive, p.cmd, array_to_string(p.roles, ', '),
        case when p.qual is not null then E'\n  USING ('||p.qual||')' else '' end,
        case when p.with_check is not null then E'\n  WITH CHECK ('||p.with_check||')' else '' end) order by p.schemaname, p.tablename, p.policyname) from pg_policies p where p.schemaname in ('public','app_private')),
   'tabela_grants', (select json_agg(x order by x) from (select format('%I.%I|%s|%s', n.nspname, c.relname, case when a.grantee = 0 then 'PUBLIC' else pg_get_userbyid(a.grantee) end, string_agg(a.privilege_type, ',' order by a.privilege_type)) x
        from pg_class c join pg_namespace n on n.oid = c.relnamespace, aclexplode(c.relacl) a
        where n.nspname in ('public','app_private') and c.relkind = 'r' and a.grantee <> c.relowner group by n.nspname, c.relname, a.grantee) s),
   'schema_acl', (select json_agg(nspname||'|'||coalesce(nspacl::text,'')) from pg_namespace where nspname in ('public','app_private'))
 )
) as catalogo;
