/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ContagemDeEstoqueRouteImport } from './routes/contagem-de-estoque'
import { Route as ControleDeEstoqueRouteImport } from './routes/controle-de-estoque'
import { Route as ControleDeFerramentasRouteImport } from './routes/controle-de-ferramentas'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as InventarioDeEstoqueRouteImport } from './routes/inventario-de-estoque'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as ReembolsoRouteImport } from './routes/reembolso'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedAssinaturaNecessariaRouteImport } from './routes/_authenticated/assinatura-necessaria'
import { Route as AuthenticatedBemVindoRouteImport } from './routes/_authenticated/bem-vindo'
import { Route as AuthenticatedConferenciaUnicaRouteImport } from './routes/_authenticated/conferencia-unica'
import { Route as AuthenticatedEmpresaBloqueadaRouteImport } from './routes/_authenticated/empresa-bloqueada'
import { Route as AuthenticatedEmpresaNovaRouteImport } from './routes/_authenticated/empresa-nova'
import { Route as AuthenticatedEstoqueAgricolaRouteImport } from './routes/_authenticated/estoque-agricola'
import { Route as AuthenticatedEstoqueIndustriaRouteImport } from './routes/_authenticated/estoque-industria'
import { Route as AuthenticatedFaturasRouteImport } from './routes/_authenticated/faturas'
import { Route as AuthenticatedFerramentasAgricolaRouteImport } from './routes/_authenticated/ferramentas-agricola'
import { Route as AuthenticatedFerramentasIndustriaRouteImport } from './routes/_authenticated/ferramentas-industria'
import { Route as AuthenticatedFrotaRouteImport } from './routes/_authenticated/frota'
import { Route as AuthenticatedMasterRouteImport } from './routes/_authenticated/master'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSecaoRouteImport } from './routes/_authenticated/admin.$secao'
import { Route as AuthenticatedMModuloRouteImport } from './routes/_authenticated/m.$modulo'
import { Route as AuthenticatedMasterIndexRouteImport } from './routes/_authenticated/master.index'
import { Route as AuthenticatedMasterAuditoriaRouteImport } from './routes/_authenticated/master.auditoria'
import { Route as AuthenticatedMasterEmpresasRouteImport } from './routes/_authenticated/master.empresas'
import { Route as AuthenticatedUnidadeIdRouteImport } from './routes/_authenticated/unidade.$id'
import { Route as ApiPublicHooksMonitorConferenciasRouteImport } from './routes/api/public/hooks/monitor-conferencias'
import { Route as ApiPublicPaymentsMercadopagoRouteImport } from './routes/api/public/payments/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ContagemDeEstoqueRoute = ContagemDeEstoqueRouteImport.update({
  id: '/contagem-de-estoque',
  path: '/contagem-de-estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ControleDeEstoqueRoute = ControleDeEstoqueRouteImport.update({
  id: '/controle-de-estoque',
  path: '/controle-de-estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ControleDeFerramentasRoute = ControleDeFerramentasRouteImport.update({
  id: '/controle-de-ferramentas',
  path: '/controle-de-ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioDeEstoqueRoute = InventarioDeEstoqueRouteImport.update({
  id: '/inventario-de-estoque',
  path: '/inventario-de-estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsoRoute = ReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturaNecessariaRoute =
  AuthenticatedAssinaturaNecessariaRouteImport.update({
    id: '/assinatura-necessaria',
    path: '/assinatura-necessaria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBemVindoRoute = AuthenticatedBemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConferenciaUnicaRoute =
  AuthenticatedConferenciaUnicaRouteImport.update({
    id: '/conferencia-unica',
    path: '/conferencia-unica',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresaBloqueadaRoute =
  AuthenticatedEmpresaBloqueadaRouteImport.update({
    id: '/empresa-bloqueada',
    path: '/empresa-bloqueada',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresaNovaRoute =
  AuthenticatedEmpresaNovaRouteImport.update({
    id: '/empresa-nova',
    path: '/empresa-nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueAgricolaRoute =
  AuthenticatedEstoqueAgricolaRouteImport.update({
    id: '/estoque-agricola',
    path: '/estoque-agricola',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueIndustriaRoute =
  AuthenticatedEstoqueIndustriaRouteImport.update({
    id: '/estoque-industria',
    path: '/estoque-industria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFaturasRoute = AuthenticatedFaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFerramentasAgricolaRoute =
  AuthenticatedFerramentasAgricolaRouteImport.update({
    id: '/ferramentas-agricola',
    path: '/ferramentas-agricola',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFerramentasIndustriaRoute =
  AuthenticatedFerramentasIndustriaRouteImport.update({
    id: '/ferramentas-industria',
    path: '/ferramentas-industria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFrotaRoute = AuthenticatedFrotaRouteImport.update({
  id: '/frota',
  path: '/frota',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterRoute = AuthenticatedMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSecaoRoute = AuthenticatedAdminSecaoRouteImport.update({
  id: '/$secao',
  path: '/$secao',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedMModuloRoute = AuthenticatedMModuloRouteImport.update({
  id: '/m/$modulo',
  path: '/m/$modulo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterIndexRoute =
  AuthenticatedMasterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterAuditoriaRoute =
  AuthenticatedMasterAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedMasterEmpresasRoute =
  AuthenticatedMasterEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedMasterRoute,
  } as any)
const AuthenticatedUnidadeIdRoute = AuthenticatedUnidadeIdRouteImport.update({
  id: '/unidade/$id',
  path: '/unidade/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksMonitorConferenciasRoute =
  ApiPublicHooksMonitorConferenciasRouteImport.update({
    id: '/api/public/hooks/monitor-conferencias',
    path: '/api/public/hooks/monitor-conferencias',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsMercadopagoRoute =
  ApiPublicPaymentsMercadopagoRouteImport.update({
    id: '/api/public/payments/mercadopago',
    path: '/api/public/payments/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contagem-de-estoque': typeof ContagemDeEstoqueRoute
  '/controle-de-estoque': typeof ControleDeEstoqueRoute
  '/controle-de-ferramentas': typeof ControleDeFerramentasRoute
  '/entrar': typeof EntrarRoute
  '/inventario-de-estoque': typeof InventarioDeEstoqueRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/reembolso': typeof ReembolsoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/assinatura-necessaria': typeof AuthenticatedAssinaturaNecessariaRoute
  '/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/conferencia-unica': typeof AuthenticatedConferenciaUnicaRoute
  '/empresa-bloqueada': typeof AuthenticatedEmpresaBloqueadaRoute
  '/empresa-nova': typeof AuthenticatedEmpresaNovaRoute
  '/estoque-agricola': typeof AuthenticatedEstoqueAgricolaRoute
  '/estoque-industria': typeof AuthenticatedEstoqueIndustriaRoute
  '/faturas': typeof AuthenticatedFaturasRoute
  '/ferramentas-agricola': typeof AuthenticatedFerramentasAgricolaRoute
  '/ferramentas-industria': typeof AuthenticatedFerramentasIndustriaRoute
  '/frota': typeof AuthenticatedFrotaRoute
  '/master': typeof AuthenticatedMasterRouteWithChildren
  '/menu': typeof AuthenticatedMenuRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/admin/$secao': typeof AuthenticatedAdminSecaoRoute
  '/m/$modulo': typeof AuthenticatedMModuloRoute
  '/master/auditoria': typeof AuthenticatedMasterAuditoriaRoute
  '/master/empresas': typeof AuthenticatedMasterEmpresasRoute
  '/unidade/$id': typeof AuthenticatedUnidadeIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/master/': typeof AuthenticatedMasterIndexRoute
  '/api/public/hooks/monitor-conferencias': typeof ApiPublicHooksMonitorConferenciasRoute
  '/api/public/payments/mercadopago': typeof ApiPublicPaymentsMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contagem-de-estoque': typeof ContagemDeEstoqueRoute
  '/controle-de-estoque': typeof ControleDeEstoqueRoute
  '/controle-de-ferramentas': typeof ControleDeFerramentasRoute
  '/entrar': typeof EntrarRoute
  '/inventario-de-estoque': typeof InventarioDeEstoqueRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/reembolso': typeof ReembolsoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/assinatura-necessaria': typeof AuthenticatedAssinaturaNecessariaRoute
  '/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/conferencia-unica': typeof AuthenticatedConferenciaUnicaRoute
  '/empresa-bloqueada': typeof AuthenticatedEmpresaBloqueadaRoute
  '/empresa-nova': typeof AuthenticatedEmpresaNovaRoute
  '/estoque-agricola': typeof AuthenticatedEstoqueAgricolaRoute
  '/estoque-industria': typeof AuthenticatedEstoqueIndustriaRoute
  '/faturas': typeof AuthenticatedFaturasRoute
  '/ferramentas-agricola': typeof AuthenticatedFerramentasAgricolaRoute
  '/ferramentas-industria': typeof AuthenticatedFerramentasIndustriaRoute
  '/frota': typeof AuthenticatedFrotaRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/admin/$secao': typeof AuthenticatedAdminSecaoRoute
  '/m/$modulo': typeof AuthenticatedMModuloRoute
  '/master/auditoria': typeof AuthenticatedMasterAuditoriaRoute
  '/master/empresas': typeof AuthenticatedMasterEmpresasRoute
  '/unidade/$id': typeof AuthenticatedUnidadeIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/master': typeof AuthenticatedMasterIndexRoute
  '/api/public/hooks/monitor-conferencias': typeof ApiPublicHooksMonitorConferenciasRoute
  '/api/public/payments/mercadopago': typeof ApiPublicPaymentsMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/contagem-de-estoque': typeof ContagemDeEstoqueRoute
  '/controle-de-estoque': typeof ControleDeEstoqueRoute
  '/controle-de-ferramentas': typeof ControleDeFerramentasRoute
  '/entrar': typeof EntrarRoute
  '/inventario-de-estoque': typeof InventarioDeEstoqueRoute
  '/precos': typeof PrecosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/reembolso': typeof ReembolsoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/assinatura-necessaria': typeof AuthenticatedAssinaturaNecessariaRoute
  '/_authenticated/bem-vindo': typeof AuthenticatedBemVindoRoute
  '/_authenticated/conferencia-unica': typeof AuthenticatedConferenciaUnicaRoute
  '/_authenticated/empresa-bloqueada': typeof AuthenticatedEmpresaBloqueadaRoute
  '/_authenticated/empresa-nova': typeof AuthenticatedEmpresaNovaRoute
  '/_authenticated/estoque-agricola': typeof AuthenticatedEstoqueAgricolaRoute
  '/_authenticated/estoque-industria': typeof AuthenticatedEstoqueIndustriaRoute
  '/_authenticated/faturas': typeof AuthenticatedFaturasRoute
  '/_authenticated/ferramentas-agricola': typeof AuthenticatedFerramentasAgricolaRoute
  '/_authenticated/ferramentas-industria': typeof AuthenticatedFerramentasIndustriaRoute
  '/_authenticated/frota': typeof AuthenticatedFrotaRoute
  '/_authenticated/master': typeof AuthenticatedMasterRouteWithChildren
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/admin/$secao': typeof AuthenticatedAdminSecaoRoute
  '/_authenticated/m/$modulo': typeof AuthenticatedMModuloRoute
  '/_authenticated/master/auditoria': typeof AuthenticatedMasterAuditoriaRoute
  '/_authenticated/master/empresas': typeof AuthenticatedMasterEmpresasRoute
  '/_authenticated/unidade/$id': typeof AuthenticatedUnidadeIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/master/': typeof AuthenticatedMasterIndexRoute
  '/api/public/hooks/monitor-conferencias': typeof ApiPublicHooksMonitorConferenciasRoute
  '/api/public/payments/mercadopago': typeof ApiPublicPaymentsMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contagem-de-estoque'
    | '/controle-de-estoque'
    | '/controle-de-ferramentas'
    | '/entrar'
    | '/inventario-de-estoque'
    | '/precos'
    | '/privacidade'
    | '/redefinir-senha'
    | '/reembolso'
    | '/sitemap.xml'
    | '/termos'
    | '/admin'
    | '/assinatura'
    | '/assinatura-necessaria'
    | '/bem-vindo'
    | '/conferencia-unica'
    | '/empresa-bloqueada'
    | '/empresa-nova'
    | '/estoque-agricola'
    | '/estoque-industria'
    | '/faturas'
    | '/ferramentas-agricola'
    | '/ferramentas-industria'
    | '/frota'
    | '/master'
    | '/menu'
    | '/planos'
    | '/admin/$secao'
    | '/m/$modulo'
    | '/master/auditoria'
    | '/master/empresas'
    | '/unidade/$id'
    | '/admin/'
    | '/master/'
    | '/api/public/hooks/monitor-conferencias'
    | '/api/public/payments/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contagem-de-estoque'
    | '/controle-de-estoque'
    | '/controle-de-ferramentas'
    | '/entrar'
    | '/inventario-de-estoque'
    | '/precos'
    | '/privacidade'
    | '/redefinir-senha'
    | '/reembolso'
    | '/sitemap.xml'
    | '/termos'
    | '/assinatura'
    | '/assinatura-necessaria'
    | '/bem-vindo'
    | '/conferencia-unica'
    | '/empresa-bloqueada'
    | '/empresa-nova'
    | '/estoque-agricola'
    | '/estoque-industria'
    | '/faturas'
    | '/ferramentas-agricola'
    | '/ferramentas-industria'
    | '/frota'
    | '/menu'
    | '/planos'
    | '/admin/$secao'
    | '/m/$modulo'
    | '/master/auditoria'
    | '/master/empresas'
    | '/unidade/$id'
    | '/admin'
    | '/master'
    | '/api/public/hooks/monitor-conferencias'
    | '/api/public/payments/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contagem-de-estoque'
    | '/controle-de-estoque'
    | '/controle-de-ferramentas'
    | '/entrar'
    | '/inventario-de-estoque'
    | '/precos'
    | '/privacidade'
    | '/redefinir-senha'
    | '/reembolso'
    | '/sitemap.xml'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/assinatura'
    | '/_authenticated/assinatura-necessaria'
    | '/_authenticated/bem-vindo'
    | '/_authenticated/conferencia-unica'
    | '/_authenticated/empresa-bloqueada'
    | '/_authenticated/empresa-nova'
    | '/_authenticated/estoque-agricola'
    | '/_authenticated/estoque-industria'
    | '/_authenticated/faturas'
    | '/_authenticated/ferramentas-agricola'
    | '/_authenticated/ferramentas-industria'
    | '/_authenticated/frota'
    | '/_authenticated/master'
    | '/_authenticated/menu'
    | '/_authenticated/planos'
    | '/_authenticated/admin/$secao'
    | '/_authenticated/m/$modulo'
    | '/_authenticated/master/auditoria'
    | '/_authenticated/master/empresas'
    | '/_authenticated/unidade/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/master/'
    | '/api/public/hooks/monitor-conferencias'
    | '/api/public/payments/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ContagemDeEstoqueRoute: typeof ContagemDeEstoqueRoute
  ControleDeEstoqueRoute: typeof ControleDeEstoqueRoute
  ControleDeFerramentasRoute: typeof ControleDeFerramentasRoute
  EntrarRoute: typeof EntrarRoute
  InventarioDeEstoqueRoute: typeof InventarioDeEstoqueRoute
  PrecosRoute: typeof PrecosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  ReembolsoRoute: typeof ReembolsoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  ApiPublicHooksMonitorConferenciasRoute: typeof ApiPublicHooksMonitorConferenciasRoute
  ApiPublicPaymentsMercadopagoRoute: typeof ApiPublicPaymentsMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contagem-de-estoque': {
      id: '/contagem-de-estoque'
      path: '/contagem-de-estoque'
      fullPath: '/contagem-de-estoque'
      preLoaderRoute: typeof ContagemDeEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controle-de-estoque': {
      id: '/controle-de-estoque'
      path: '/controle-de-estoque'
      fullPath: '/controle-de-estoque'
      preLoaderRoute: typeof ControleDeEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controle-de-ferramentas': {
      id: '/controle-de-ferramentas'
      path: '/controle-de-ferramentas'
      fullPath: '/controle-de-ferramentas'
      preLoaderRoute: typeof ControleDeFerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario-de-estoque': {
      id: '/inventario-de-estoque'
      path: '/inventario-de-estoque'
      fullPath: '/inventario-de-estoque'
      preLoaderRoute: typeof InventarioDeEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolso': {
      id: '/reembolso'
      path: '/reembolso'
      fullPath: '/reembolso'
      preLoaderRoute: typeof ReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura-necessaria': {
      id: '/_authenticated/assinatura-necessaria'
      path: '/assinatura-necessaria'
      fullPath: '/assinatura-necessaria'
      preLoaderRoute: typeof AuthenticatedAssinaturaNecessariaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bem-vindo': {
      id: '/_authenticated/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof AuthenticatedBemVindoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conferencia-unica': {
      id: '/_authenticated/conferencia-unica'
      path: '/conferencia-unica'
      fullPath: '/conferencia-unica'
      preLoaderRoute: typeof AuthenticatedConferenciaUnicaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa-bloqueada': {
      id: '/_authenticated/empresa-bloqueada'
      path: '/empresa-bloqueada'
      fullPath: '/empresa-bloqueada'
      preLoaderRoute: typeof AuthenticatedEmpresaBloqueadaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa-nova': {
      id: '/_authenticated/empresa-nova'
      path: '/empresa-nova'
      fullPath: '/empresa-nova'
      preLoaderRoute: typeof AuthenticatedEmpresaNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque-agricola': {
      id: '/_authenticated/estoque-agricola'
      path: '/estoque-agricola'
      fullPath: '/estoque-agricola'
      preLoaderRoute: typeof AuthenticatedEstoqueAgricolaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque-industria': {
      id: '/_authenticated/estoque-industria'
      path: '/estoque-industria'
      fullPath: '/estoque-industria'
      preLoaderRoute: typeof AuthenticatedEstoqueIndustriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faturas': {
      id: '/_authenticated/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof AuthenticatedFaturasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ferramentas-agricola': {
      id: '/_authenticated/ferramentas-agricola'
      path: '/ferramentas-agricola'
      fullPath: '/ferramentas-agricola'
      preLoaderRoute: typeof AuthenticatedFerramentasAgricolaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ferramentas-industria': {
      id: '/_authenticated/ferramentas-industria'
      path: '/ferramentas-industria'
      fullPath: '/ferramentas-industria'
      preLoaderRoute: typeof AuthenticatedFerramentasIndustriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/frota': {
      id: '/_authenticated/frota'
      path: '/frota'
      fullPath: '/frota'
      preLoaderRoute: typeof AuthenticatedFrotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master': {
      id: '/_authenticated/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedMasterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$secao': {
      id: '/_authenticated/admin/$secao'
      path: '/$secao'
      fullPath: '/admin/$secao'
      preLoaderRoute: typeof AuthenticatedAdminSecaoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/m/$modulo': {
      id: '/_authenticated/m/$modulo'
      path: '/m/$modulo'
      fullPath: '/m/$modulo'
      preLoaderRoute: typeof AuthenticatedMModuloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/': {
      id: '/_authenticated/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof AuthenticatedMasterIndexRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/auditoria': {
      id: '/_authenticated/master/auditoria'
      path: '/auditoria'
      fullPath: '/master/auditoria'
      preLoaderRoute: typeof AuthenticatedMasterAuditoriaRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/master/empresas': {
      id: '/_authenticated/master/empresas'
      path: '/empresas'
      fullPath: '/master/empresas'
      preLoaderRoute: typeof AuthenticatedMasterEmpresasRouteImport
      parentRoute: typeof AuthenticatedMasterRoute
    }
    '/_authenticated/unidade/$id': {
      id: '/_authenticated/unidade/$id'
      path: '/unidade/$id'
      fullPath: '/unidade/$id'
      preLoaderRoute: typeof AuthenticatedUnidadeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/monitor-conferencias': {
      id: '/api/public/hooks/monitor-conferencias'
      path: '/api/public/hooks/monitor-conferencias'
      fullPath: '/api/public/hooks/monitor-conferencias'
      preLoaderRoute: typeof ApiPublicHooksMonitorConferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/mercadopago': {
      id: '/api/public/payments/mercadopago'
      path: '/api/public/payments/mercadopago'
      fullPath: '/api/public/payments/mercadopago'
      preLoaderRoute: typeof ApiPublicPaymentsMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminSecaoRoute: typeof AuthenticatedAdminSecaoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminSecaoRoute: AuthenticatedAdminSecaoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMasterRouteChildren {
  AuthenticatedMasterAuditoriaRoute: typeof AuthenticatedMasterAuditoriaRoute
  AuthenticatedMasterEmpresasRoute: typeof AuthenticatedMasterEmpresasRoute
  AuthenticatedMasterIndexRoute: typeof AuthenticatedMasterIndexRoute
}

const AuthenticatedMasterRouteChildren: AuthenticatedMasterRouteChildren = {
  AuthenticatedMasterAuditoriaRoute: AuthenticatedMasterAuditoriaRoute,
  AuthenticatedMasterEmpresasRoute: AuthenticatedMasterEmpresasRoute,
  AuthenticatedMasterIndexRoute: AuthenticatedMasterIndexRoute,
}

const AuthenticatedMasterRouteWithChildren =
  AuthenticatedMasterRoute._addFileChildren(AuthenticatedMasterRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedAssinaturaNecessariaRoute: typeof AuthenticatedAssinaturaNecessariaRoute
  AuthenticatedBemVindoRoute: typeof AuthenticatedBemVindoRoute
  AuthenticatedConferenciaUnicaRoute: typeof AuthenticatedConferenciaUnicaRoute
  AuthenticatedEmpresaBloqueadaRoute: typeof AuthenticatedEmpresaBloqueadaRoute
  AuthenticatedEmpresaNovaRoute: typeof AuthenticatedEmpresaNovaRoute
  AuthenticatedEstoqueAgricolaRoute: typeof AuthenticatedEstoqueAgricolaRoute
  AuthenticatedEstoqueIndustriaRoute: typeof AuthenticatedEstoqueIndustriaRoute
  AuthenticatedFaturasRoute: typeof AuthenticatedFaturasRoute
  AuthenticatedFerramentasAgricolaRoute: typeof AuthenticatedFerramentasAgricolaRoute
  AuthenticatedFerramentasIndustriaRoute: typeof AuthenticatedFerramentasIndustriaRoute
  AuthenticatedFrotaRoute: typeof AuthenticatedFrotaRoute
  AuthenticatedMasterRoute: typeof AuthenticatedMasterRouteWithChildren
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedMModuloRoute: typeof AuthenticatedMModuloRoute
  AuthenticatedUnidadeIdRoute: typeof AuthenticatedUnidadeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedAssinaturaNecessariaRoute:
    AuthenticatedAssinaturaNecessariaRoute,
  AuthenticatedBemVindoRoute: AuthenticatedBemVindoRoute,
  AuthenticatedConferenciaUnicaRoute: AuthenticatedConferenciaUnicaRoute,
  AuthenticatedEmpresaBloqueadaRoute: AuthenticatedEmpresaBloqueadaRoute,
  AuthenticatedEmpresaNovaRoute: AuthenticatedEmpresaNovaRoute,
  AuthenticatedEstoqueAgricolaRoute: AuthenticatedEstoqueAgricolaRoute,
  AuthenticatedEstoqueIndustriaRoute: AuthenticatedEstoqueIndustriaRoute,
  AuthenticatedFaturasRoute: AuthenticatedFaturasRoute,
  AuthenticatedFerramentasAgricolaRoute: AuthenticatedFerramentasAgricolaRoute,
  AuthenticatedFerramentasIndustriaRoute:
    AuthenticatedFerramentasIndustriaRoute,
  AuthenticatedFrotaRoute: AuthenticatedFrotaRoute,
  AuthenticatedMasterRoute: AuthenticatedMasterRouteWithChildren,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedMModuloRoute: AuthenticatedMModuloRoute,
  AuthenticatedUnidadeIdRoute: AuthenticatedUnidadeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ContagemDeEstoqueRoute: ContagemDeEstoqueRoute,
  ControleDeEstoqueRoute: ControleDeEstoqueRoute,
  ControleDeFerramentasRoute: ControleDeFerramentasRoute,
  EntrarRoute: EntrarRoute,
  InventarioDeEstoqueRoute: InventarioDeEstoqueRoute,
  PrecosRoute: PrecosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  ReembolsoRoute: ReembolsoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  ApiPublicHooksMonitorConferenciasRoute:
    ApiPublicHooksMonitorConferenciasRoute,
  ApiPublicPaymentsMercadopagoRoute: ApiPublicPaymentsMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
